// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"project/ent/predicate"
	"project/ent/resourceallocation"
	"project/ent/shift"
	"project/ent/staff"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShiftQuery is the builder for querying Shift entities.
type ShiftQuery struct {
	config
	ctx             *QueryContext
	order           []shift.OrderOption
	inters          []Interceptor
	predicates      []predicate.Shift
	withStaff       *StaffQuery
	withAllocations *ResourceAllocationQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ShiftQuery builder.
func (sq *ShiftQuery) Where(ps ...predicate.Shift) *ShiftQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *ShiftQuery) Limit(limit int) *ShiftQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *ShiftQuery) Offset(offset int) *ShiftQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *ShiftQuery) Unique(unique bool) *ShiftQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *ShiftQuery) Order(o ...shift.OrderOption) *ShiftQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryStaff chains the current query on the "staff" edge.
func (sq *ShiftQuery) QueryStaff() *StaffQuery {
	query := (&StaffClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(shift.Table, shift.FieldID, selector),
			sqlgraph.To(staff.Table, staff.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shift.StaffTable, shift.StaffColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAllocations chains the current query on the "allocations" edge.
func (sq *ShiftQuery) QueryAllocations() *ResourceAllocationQuery {
	query := (&ResourceAllocationClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(shift.Table, shift.FieldID, selector),
			sqlgraph.To(resourceallocation.Table, resourceallocation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, shift.AllocationsTable, shift.AllocationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Shift entity from the query.
// Returns a *NotFoundError when no Shift was found.
func (sq *ShiftQuery) First(ctx context.Context) (*Shift, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{shift.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *ShiftQuery) FirstX(ctx context.Context) *Shift {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Shift ID from the query.
// Returns a *NotFoundError when no Shift ID was found.
func (sq *ShiftQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{shift.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *ShiftQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Shift entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Shift entity is found.
// Returns a *NotFoundError when no Shift entities are found.
func (sq *ShiftQuery) Only(ctx context.Context) (*Shift, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{shift.Label}
	default:
		return nil, &NotSingularError{shift.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *ShiftQuery) OnlyX(ctx context.Context) *Shift {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Shift ID in the query.
// Returns a *NotSingularError when more than one Shift ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *ShiftQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{shift.Label}
	default:
		err = &NotSingularError{shift.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *ShiftQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Shifts.
func (sq *ShiftQuery) All(ctx context.Context) ([]*Shift, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Shift, *ShiftQuery]()
	return withInterceptors[[]*Shift](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *ShiftQuery) AllX(ctx context.Context) []*Shift {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Shift IDs.
func (sq *ShiftQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(shift.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *ShiftQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *ShiftQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*ShiftQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *ShiftQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *ShiftQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *ShiftQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ShiftQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *ShiftQuery) Clone() *ShiftQuery {
	if sq == nil {
		return nil
	}
	return &ShiftQuery{
		config:          sq.config,
		ctx:             sq.ctx.Clone(),
		order:           append([]shift.OrderOption{}, sq.order...),
		inters:          append([]Interceptor{}, sq.inters...),
		predicates:      append([]predicate.Shift{}, sq.predicates...),
		withStaff:       sq.withStaff.Clone(),
		withAllocations: sq.withAllocations.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithStaff tells the query-builder to eager-load the nodes that are connected to
// the "staff" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *ShiftQuery) WithStaff(opts ...func(*StaffQuery)) *ShiftQuery {
	query := (&StaffClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withStaff = query
	return sq
}

// WithAllocations tells the query-builder to eager-load the nodes that are connected to
// the "allocations" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *ShiftQuery) WithAllocations(opts ...func(*ResourceAllocationQuery)) *ShiftQuery {
	query := (&ResourceAllocationClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withAllocations = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StartTime time.Time `json:"start_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Shift.Query().
//		GroupBy(shift.FieldStartTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *ShiftQuery) GroupBy(field string, fields ...string) *ShiftGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ShiftGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = shift.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StartTime time.Time `json:"start_time,omitempty"`
//	}
//
//	client.Shift.Query().
//		Select(shift.FieldStartTime).
//		Scan(ctx, &v)
func (sq *ShiftQuery) Select(fields ...string) *ShiftSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &ShiftSelect{ShiftQuery: sq}
	sbuild.label = shift.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ShiftSelect configured with the given aggregations.
func (sq *ShiftQuery) Aggregate(fns ...AggregateFunc) *ShiftSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *ShiftQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !shift.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *ShiftQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Shift, error) {
	var (
		nodes       = []*Shift{}
		withFKs     = sq.withFKs
		_spec       = sq.querySpec()
		loadedTypes = [2]bool{
			sq.withStaff != nil,
			sq.withAllocations != nil,
		}
	)
	if sq.withStaff != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, shift.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Shift).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Shift{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withStaff; query != nil {
		if err := sq.loadStaff(ctx, query, nodes, nil,
			func(n *Shift, e *Staff) { n.Edges.Staff = e }); err != nil {
			return nil, err
		}
	}
	if query := sq.withAllocations; query != nil {
		if err := sq.loadAllocations(ctx, query, nodes,
			func(n *Shift) { n.Edges.Allocations = []*ResourceAllocation{} },
			func(n *Shift, e *ResourceAllocation) { n.Edges.Allocations = append(n.Edges.Allocations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *ShiftQuery) loadStaff(ctx context.Context, query *StaffQuery, nodes []*Shift, init func(*Shift), assign func(*Shift, *Staff)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Shift)
	for i := range nodes {
		if nodes[i].staff_shifts == nil {
			continue
		}
		fk := *nodes[i].staff_shifts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(staff.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "staff_shifts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sq *ShiftQuery) loadAllocations(ctx context.Context, query *ResourceAllocationQuery, nodes []*Shift, init func(*Shift), assign func(*Shift, *ResourceAllocation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Shift)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ResourceAllocation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(shift.AllocationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.shift_allocations
		if fk == nil {
			return fmt.Errorf(`foreign-key "shift_allocations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "shift_allocations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sq *ShiftQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *ShiftQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(shift.Table, shift.Columns, sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shift.FieldID)
		for i := range fields {
			if fields[i] != shift.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *ShiftQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(shift.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = shift.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ShiftGroupBy is the group-by builder for Shift entities.
type ShiftGroupBy struct {
	selector
	build *ShiftQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *ShiftGroupBy) Aggregate(fns ...AggregateFunc) *ShiftGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *ShiftGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShiftQuery, *ShiftGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *ShiftGroupBy) sqlScan(ctx context.Context, root *ShiftQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ShiftSelect is the builder for selecting fields of Shift entities.
type ShiftSelect struct {
	*ShiftQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *ShiftSelect) Aggregate(fns ...AggregateFunc) *ShiftSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *ShiftSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShiftQuery, *ShiftSelect](ctx, ss.ShiftQuery, ss, ss.inters, v)
}

func (ss *ShiftSelect) sqlScan(ctx context.Context, root *ShiftQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
